"""add cascade delete

Revision ID: ccad5272d49c
Revises: a15483a6e403
Create Date: 2026-03-30 11:42:45.884598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccad5272d49c'
down_revision: Union[str, Sequence[str], None] = 'a15483a6e403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('flashcards_deck_id_fkey'), 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key(op.f('flashcards_deck_id_fkey'), 'flashcards', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###
